baseURL = 'http://localhost:1313/'
languageCode = 'en-US'
title = 'The Black Circle'
theme = 'the-black-circle'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[caches]
  [caches.images]
    dir = ':cacheDir/images'